language: go

go_import_path: kubesphere.io/devops

go:
  - "1.10.3"

sudo: required

services:
- docker

before_script:
- docker --version

install:
  - chmod +x hack/*.sh
  - go get golang.org/x/tools/cmd/goimports

scripts:
  - make check
  - make test

deploy:
- provider: script
  script: bash hack/docker_push.sh latest
  on:
    branch: master
    repo: kubesphere/devops

- provider: script
  script: bash docker_push $TRAVIS_TAG
  on:
    tags: true
    repo: kubesphere/devops
