language: go

go_import_path: kubesphere.io/devops

go:
  - "1.10.3"

sudo: required

services:
- docker

before_script:
- docker --version

install:
  - chmod +x hack/*.sh
  - go get golang.org/x/tools/cmd/goimports

script:
  - make test

deploy:
  - provider: script
    script: bash hack/docker_push.sh advanced-2.0.0-dev
    on:
      branch: master
      repo: kubesphere/devops
